// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// PI_C
NumericMatrix PI_C(List lrbs, DataFrame x, double alpha);
RcppExport SEXP _STA141CFinal_PI_C(SEXP lrbsSEXP, SEXP xSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lrbs(lrbsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(PI_C(lrbs, x, alpha));
    return rcpp_result_gen;
END_RCPP
}
// coef_CI_C
NumericMatrix coef_CI_C(List lrbs, double alpha);
RcppExport SEXP _STA141CFinal_coef_CI_C(SEXP lrbsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lrbs(lrbsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(coef_CI_C(lrbs, alpha));
    return rcpp_result_gen;
END_RCPP
}
// linear_reg_bs_C
List linear_reg_bs_C(DataFrame x, arma::colvec y, int s, int r);
RcppExport SEXP _STA141CFinal_linear_reg_bs_C(SEXP xSEXP, SEXP ySEXP, SEXP sSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_reg_bs_C(x, y, s, r));
    return rcpp_result_gen;
END_RCPP
}
// s2_CI_C
NumericVector s2_CI_C(List lrbs, double alpha);
RcppExport SEXP _STA141CFinal_s2_CI_C(SEXP lrbsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lrbs(lrbsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(s2_CI_C(lrbs, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STA141CFinal_PI_C", (DL_FUNC) &_STA141CFinal_PI_C, 3},
    {"_STA141CFinal_coef_CI_C", (DL_FUNC) &_STA141CFinal_coef_CI_C, 2},
    {"_STA141CFinal_linear_reg_bs_C", (DL_FUNC) &_STA141CFinal_linear_reg_bs_C, 4},
    {"_STA141CFinal_s2_CI_C", (DL_FUNC) &_STA141CFinal_s2_CI_C, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_STA141CFinal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
