# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PI_C <- function(lrbs, x, alpha) {
    .Call(`_STA141CFinal_PI_C`, lrbs, x, alpha)
}

coef_CI_C <- function(lrbs, alpha) {
    .Call(`_STA141CFinal_coef_CI_C`, lrbs, alpha)
}

linear_reg_bs_C <- function(x, y, s, r) {
    .Call(`_STA141CFinal_linear_reg_bs_C`, x, y, s, r)
}

s2_CI_C <- function(lrbs, alpha) {
    .Call(`_STA141CFinal_s2_CI_C`, lrbs, alpha)
}

